config/routes.rb
Rails.application.routes.draw do
  
  resources :resumes
  resources :tasks do
    put :sort, on: :collection
  end
  resources :multistep_forms

  get '/form_preview' => "multistep_submissions#multistep_form_preview"
  post '/save_multiplestep_form' => "multistep_submissions#save_multiplestep_form"
  resources :submissions, only: [:index, :show]
    devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
   
  resources :basic_forms do 
    member do 
      get :preview_form
      get :submissions
      get :submission_data_to_csv
    end
    collection do 
      post :collect_user_response
    end
    put :sort_blocks, on: :collection
    put :sort_multiple_choices, on: :collection
    put :sort_checkbox_questions, on: :collection
    put :sort_dropdowns, on: :collection
  end
  resources :custom_forms
  resources :feedback_forms
  root 'home#index'

  resources :forms

  get '/dropdown_conditional_block' => "condition_levels#dropdown_conditional_block"
  get '/form_block_conditional_block' => "condition_levels#form_block_conditional_block"
  get '/mcq_conditional_block' => "condition_levels#mcq_conditional_block"
  get '/checkbox_conditional_block' => "condition_levels#checkbox_conditional_block"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/multistep_forms_controller.rb
class MultistepFormsController < ApplicationController
  before_action :set_multistep_form, only: [:show, :edit, :update, :destroy]

  # GET /multistep_forms
  # GET /multistep_forms.json
  def index
    @multistep_forms = MultistepForm.all
  end

  # GET /multistep_forms/1
  # GET /multistep_forms/1.json
  def show
  end

  # GET /multistep_forms/new
  def new
    @multistep_form = MultistepForm.new
  end

  # GET /multistep_forms/1/edit
  def edit
  end

  # POST /multistep_forms
  # POST /multistep_forms.json
  def create
    @multistep_form = MultistepForm.new(multistep_form_params)

    respond_to do |format|
      if @multistep_form.save
        format.html { redirect_to @multistep_form, notice: 'Multistep form was successfully created.' }
        format.json { render :show, status: :created, location: @multistep_form }
      else
        format.html { render :new }
        format.json { render json: @multistep_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /multistep_forms/1
  # PATCH/PUT /multistep_forms/1.json
  def update
    respond_to do |format|
      if @multistep_form.update(multistep_form_params)
        format.html { redirect_to @multistep_form, notice: 'Multistep form was successfully updated.' }
        format.json { render :show, status: :ok, location: @multistep_form }
      else
        format.html { render :edit }
        format.json { render json: @multistep_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /multistep_forms/1
  # DELETE /multistep_forms/1.json
  def destroy
    @multistep_form.destroy
    respond_to do |format|
      format.html { redirect_to multistep_forms_url, notice: 'Multistep form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_multistep_form
      @multistep_form = MultistepForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def multistep_form_params
      params.require(:multistep_form).permit!
    end
end

app/views/multistep_forms/_form.html.erb
<%= form_with(model: multistep_form, local: true) do |f| %>
  <% if multistep_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(multistep_form.errors.count, "error") %> prohibited this multistep_form from being saved:</h2>

      <ul>
      <% multistep_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, id: :multistep_form_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, id: :multistep_form_description, class: "form-control", rows: "5" %>
  </div>

  <div id="form_steps" class="mt-3">
    <%= f.fields_for :form_steps do |form_step| %>
      <%= render 'form_step_fields', f: form_step %>
    <% end %>
    <div class="links mb-1">
      <%= link_to_add_association 'Add Step', f, :form_steps, class: "btn btn-success" %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/multistep_forms/_form_block_fields.html.erb
<div class="nested-fields">
  <div class="">
    <div class="form-group">
      <%= f.select :field_type, options_for_select(FormBlock::FIELDTYPE), {prompt: "Select field type"}, {class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.text_field :label, class: "form-control", placeholder: "Write a label here" %>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= f.check_box :is_required, style: "height:25px;width:25px;" %>
        <%= f.label :is_required %>
      </div>
      <div class="col-md-6">
        <%= link_to_remove_association "Remove Block", f, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/multistep_forms/_form_step_fields.html.erb
<div class="nested-fields">
  <div class="jumbotron">
    <div class="form-group">
      <%= f.text_field :step_number, class: "form-control", placeholder: "Write step number" %>
    </div>
    <div class="form-group">
      <%= f.text_field :name, class: "form-control", placeholder: "Write name for step" %>
    </div>
    <div id="form_blocks" class="mt-3">
      <%= f.fields_for :form_blocks do |form_block| %>
        <%= render 'form_block_fields', f: form_block %>
      <% end %>
      <div class="links mb-1">
        <%= link_to_add_association 'Add Block', f, :form_blocks, class: "btn btn-success" %>
      </div>
    </div>
    <%= link_to_remove_association "Remove Step", f, class: "btn btn-danger" %>
  </div>
</div>

app/views/multistep_forms/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-2">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title text-center">Editing Multistep Form</h4>
        </div>
        <div class="card-body">
          <%= render 'form', multistep_form: @multistep_form %>
          <%= link_to 'Show', @multistep_form %> |
          <%= link_to 'Back', multistep_forms_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/multistep_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Multistep Forms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @multistep_forms.each do |multistep_form| %>
      <tr>
        <td><%= multistep_form.name %></td>
        <td><%= multistep_form.description %></td>
        <td><%= link_to 'Show', multistep_form %></td>
        <td><%= link_to 'Edit', edit_multistep_form_path(multistep_form) %></td>
        <td><%= link_to 'Destroy', multistep_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Multistep Form', new_multistep_form_path %>

app/views/multistep_forms/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-2">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title text-center">New Multistep Form</h4>
        </div>
        <div class="card-body">
          <%= render 'form', multistep_form: @multistep_form %>
          <%= link_to 'Back', multistep_forms_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/multistep_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @multistep_form.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @multistep_form.description %>
</p>

<%= link_to 'Edit', edit_multistep_form_path(@multistep_form) %> |
<%= link_to 'Back', multistep_forms_path %> | 
<%= link_to 'Form Preview', form_preview_path(form_id: @multistep_form.id) %>