config/routes.rb
Rails.application.routes.draw do
  
  resources :resumes
  resources :tasks do
    put :sort, on: :collection
  end
  resources :multistep_forms

  get '/form_preview' => "multistep_submissions#multistep_form_preview"
  post '/save_multiplestep_form' => "multistep_submissions#save_multiplestep_form"
  resources :submissions, only: [:index, :show]
    devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
   
  resources :basic_forms do 
    member do 
      get :preview_form
      get :submissions
      get :submission_data_to_csv
    end
    collection do 
      post :collect_user_response
    end
    put :sort_blocks, on: :collection
    put :sort_multiple_choices, on: :collection
    put :sort_checkbox_questions, on: :collection
    put :sort_dropdowns, on: :collection
  end
  resources :custom_forms
  resources :feedback_forms
  root 'home#index'

  resources :forms

  get '/dropdown_conditional_block' => "condition_levels#dropdown_conditional_block"
  get '/form_block_conditional_block' => "condition_levels#form_block_conditional_block"
  get '/mcq_conditional_block' => "condition_levels#mcq_conditional_block"
  get '/checkbox_conditional_block' => "condition_levels#checkbox_conditional_block"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :set_form, only: [:show, :edit, :update, :destroy]

  # GET /forms
  # GET /forms.json
  def index
    @forms = Form.all
  end

  # GET /forms/1
  # GET /forms/1.json
  def show
  end

  # GET /forms/new
  def new
    @form = Form.new
  end

  # GET /forms/1/edit
  def edit
  end

  # POST /forms
  # POST /forms.json
  def create
    @form = Form.new(form_params)

    respond_to do |format|
      if @form.save
        format.html { redirect_to @form, notice: 'Form was successfully created.' }
        format.json { render :show, status: :created, location: @form }
      else
        format.html { render :new }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forms/1
  # PATCH/PUT /forms/1.json
  def update
    respond_to do |format|
      if @form.update(form_params)
        format.html { redirect_to @form, notice: 'Form was successfully updated.' }
        format.json { render :show, status: :ok, location: @form }
      else
        format.html { render :edit }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1
  # DELETE /forms/1.json
  def destroy
    @form.destroy
    respond_to do |format|
      format.html { redirect_to forms_url, notice: 'Form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_params
      params.require(:form).permit(:name, :description, :is_published, form_fields_attributes: [:id, :label, :tag, :is_required, :_destroy])
    end
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<%= form_for  @form do |f| %>
  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(form.errors.count, "error") %> prohibited this form from being saved:</h2>

      <ul>
      <% @form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, id: :f_name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, id: :f_description %>
  </div>

  <div class="field">
    <%= f.label :is_published %>
    <%= f.check_box :is_published, id: :f_is_published %>
  </div>

  <div id="tasks">
    <%= f.fields_for :form_fields do |form_field| %>
      <%= render 'form_field_fields', f: form_field %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add Field', f, :form_fields %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forms/_form_field_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :label %>
    <br/>
    <%= f.text_field :label, value: "Untitled Question?" %>
  </div>
  <div class="field">
    <%= f.label :tag %>
    <br/>
    <%= f.text_field :tag, value: "Untitled Question?" %>
  </div>
  <div class="field">
    <%= f.check_box :is_required %>
    <%= f.label :is_required %>
  </div>
  <%= link_to_remove_association "remove task", f %>
</div>

app/views/forms/edit.html.erb
<h1>Editing Form</h1>

<%= render 'form', form: @form %>

<%= link_to 'Show', @form %> |
<%= link_to 'Back', forms_path %>

app/views/forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Forms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Is published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forms.each do |form| %>
      <tr>
        <td><%= form.name %></td>
        <td><%= form.description %></td>
        <td><%= form.is_published %></td>
        <td><%= link_to 'Show', form %></td>
        <td><%= link_to 'Edit', edit_form_path(form) %></td>
        <td><%= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Form', new_form_path %>

app/views/forms/new.html.erb
<h1>New Form</h1>

<%= render 'form', form: @form %>

<%= link_to 'Back', forms_path %>

app/views/forms/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @form.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @form.description %>
</p>
<p>
  <strong>Is published:</strong>
  <%= @form.is_published %>
</p>
<%= link_to 'Edit', edit_form_path(@form) %> |
<%= link_to 'Back', forms_path %>