config/routes.rb
Rails.application.routes.draw do
  
  resources :resumes
  resources :tasks do
    put :sort, on: :collection
  end
  resources :multistep_forms

  get '/form_preview' => "multistep_submissions#multistep_form_preview"
  post '/save_multiplestep_form' => "multistep_submissions#save_multiplestep_form"
  resources :submissions, only: [:index, :show]
    devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
   
  resources :basic_forms do 
    member do 
      get :preview_form
      get :submissions
      get :submission_data_to_csv
    end
    collection do 
      post :collect_user_response
    end
    put :sort_blocks, on: :collection
    put :sort_multiple_choices, on: :collection
    put :sort_checkbox_questions, on: :collection
    put :sort_dropdowns, on: :collection
  end
  resources :custom_forms
  resources :feedback_forms
  root 'home#index'

  resources :forms

  get '/dropdown_conditional_block' => "condition_levels#dropdown_conditional_block"
  get '/form_block_conditional_block' => "condition_levels#form_block_conditional_block"
  get '/mcq_conditional_block' => "condition_levels#mcq_conditional_block"
  get '/checkbox_conditional_block' => "condition_levels#checkbox_conditional_block"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/resume.rb
class Resume < ApplicationRecord
  has_many :academic_credentials, inverse_of: :resume
  has_many :achievements, inverse_of: :resume
  has_many :projects, inverse_of: :resume
  has_many :skills, inverse_of: :resume
  has_many :hobbies, inverse_of: :resume
  belongs_to :user, optional: :true
  accepts_nested_attributes_for :academic_credentials, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :achievements, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :projects, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :skills, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :hobbies, reject_if: :all_blank, allow_destroy: true
  mount_uploader :image, ImageUploader

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_resume, only: [:show, :edit, :update, :destroy]

  def index
    @resumes = current_user.resumes
  end

  def show;end

  def new
    @resume = Resume.new
  end

  def edit;end

  def create
    @resume = Resume.new(resume_params)

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url, notice: 'Resume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_resume
      @resume = Resume.find(params[:id])
    end

    def resume_params
      params.require(:resume).permit!
    end
end

app/views/resumes/_academic_credential_fields.html.erb
<div class="nested-fields">  
  <div class="form-group row">
    <div class="col-md-6">
      <%= f.label :course %>
      <%= f.text_field :course, class: "form-control" %>
    </div>
    <div class="col-md-3">
      <%= f.label :year %>
      <%= f.text_field :year,  class: "form-control" %>
    </div>
    <div class="col-md-3">
      <%= f.label :percentage %>
      <%= f.text_field :percentage,  class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-3">
      <%= f.label :grade %>
      <%= f.text_field :grade,  class: "form-control" %>
    </div>
    <div class="col-md-9">
      <%= f.label :board_or_univercity %>
      <%= f.text_field :board_or_univercity,  class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-md-6">
      <%= link_to_remove_association "Remove Academic Credential", f, class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/resumes/_achievement_fields.html.erb
<div class="nested-fields">  
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_area :title, id: :resume_title, class: "form-control", rows: "4" %>
  </div>
   <div class="form-group row">
    <div class="col-md-6">
      <%= link_to_remove_association "Remove Achievements", f, class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/resumes/_form.html.erb
<%= form_with(model: resume, local: true) do |f| %>
  <% if resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% resume.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="form-group mt-2">
    <%= f.label :Images %>
    <%= f.file_field :image %>
    <%= image_tag(@resume.image_url) if @resume.image? %>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, id: :resume_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, id: :resume_email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :contact %>
    <%= f.text_field :contact, id: :resume_contact, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, id: :resume_address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, id: :resume_city, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state, id: :resume_state, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :country %>
    <%= f.text_field :country, id: :resume_country, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :zipcode %>
    <%= f.text_field :zipcode, id: :resume_zipcode, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :objective %> <a href="javascript:void(0)" class="ml-2" data-toggle="modal" data-target="#suggestionBox">Views suggestions for better objectives</a> 
    <%= f.text_area :objective, id: :resume_objective, class: "form-control", rows: "4" %>
  </div>

  <div class="form-group">
    <%= f.label :gender %>
    <%= f.text_field :gender, id: :resume_gender, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :date_of_birth %>
    <%= f.date_select :date_of_birth, id: :resume_date_of_birth %>
  </div>

  <div class="form-group">
    <%= f.label :mother_name %>
    <%= f.text_field :mother_name, id: :resume_mother_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :father_name %>
    <%= f.text_field :father_name, id: :resume_father_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :cast %>
    <%= f.text_field :cast, id: :resume_cast, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :relegion %>
    <%= f.text_field :relegion, id: :resume_relegion, class: "form-control" %>
  </div>

  <hr>
  <div id="academic_credentials">
    <h5 class="font-weight-bold">Add your academic credentials</h5>
    <%= f.fields_for :academic_credentials do |academic_credential| %>
      <div class="card rounded-0 mb-3">
        <div class="card-body">
          <%= render 'academic_credential_fields', f: academic_credential %>      
        </div>
      </div>
    <% end %>
    <div class="links mb-1">
      <%= link_to_add_association 'Add Academic Credentials', f, :academic_credentials, class: "btn btn-success" %>
    </div> 
  </div>

  <hr>
  <div id="achievements">
    <h5 class="font-weight-bold">Add your personal and professional acheivements</h5>
    <%= f.fields_for :achievements do |achievement| %>
      <div class="card rounded-0 mb-3">
        <div class="card-body">
          <%= render 'achievement_fields', f: achievement %>         
        </div>
      </div>
    <% end %>
    <div class="links mb-1">
      <%= link_to_add_association 'Add Achievements', f, :achievements, class: "btn btn-success" %>
    </div>
  </div>

  <hr>
  <div id="projects">
    <h5 class="font-weight-bold">Add your projects which can help to make a good impressive resume</h5>
    <%= f.fields_for :projects do |project| %>
      <div class="card rounded-0 mb-3">
        <div class="card-body">
          <%= render 'project_fields', f: project %>         
        </div>
      </div>
    <% end %>
    <div class="links mb-1">
      <%= link_to_add_association 'Add Project', f, :projects, class: "btn btn-success" %>
    </div>
  </div>

  <div id="skills">
    <h5 class="font-weight-bold">Add your skills</h5>
    <%= f.fields_for :skills do |skill| %>
      <div class="card rounded-0 mb-3">
        <div class="card-body">
          <%= render 'skill_fields', f: skill %>         
        </div>
      </div>
    <% end %>
    <div class="links mb-1">
      <%= link_to_add_association 'Add skills', f, :skills, class: "btn btn-success" %>
    </div>
  </div>

   <div id="hobbies">
    <h5 class="font-weight-bold">Add your hobbies</h5>
    <%= f.fields_for :hobbies do |hobby| %>
      <div class="card rounded-0 mb-3">
        <div class="card-body">
          <%= render 'hobby_fields', f: hobby %>         
        </div>
      </div>
    <% end %>
    <div class="links mb-1">
      <%= link_to_add_association 'Add hobbies', f, :hobbies, class: "btn btn-success" %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary btn-lg' %>
    <%= link_to 'Back', resumes_path, class: 'btn btn-outline-primary btn-lg' %>
  </div>
<% end %>


<div class="modal fade" id="suggestionBox" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content rounded-0">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">How to write better objectives</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="mb-3">
          <h6 class="font-weight-bold">What is a Resume Objective?</h6>
          <p class="font-14">A resume objective is a statement of your goals for employment, usually listed at the top of your resume. A resume objective is typically one or two sentences long.</p>
          <p class="font-14">The most effective objective is one that is tailored to the job you are applying for. It states what kind of career you are seeking, and what skills and experiences you have that make you ideal for that career. A resume objective might also include where you have been and where you want to go in your career.</p>
          <p class="font-14">For example, it might state some of your past accomplishments, and then move on to the kinds of accomplishments you hope to achieve in the future (ideally, accomplishments you want to achieve for the company you are applying to).</p>
          <p class="font-14">Ultimately, stating an objective is optional, but it can help convince employers that you know what you want and are familiar with the industry.</p>
        </div>
        <div class="mb-3">
          <h6 class="font-weight-bold">When to Use a Resume Objective?</h6>
          <p class="font-14">Again, some career experts find resume objectives outdated. However, there are times when a resume objective can be very useful. Whenever you want to emphasize that you are ambitious, that you know what you want in a career, or that you have the skills for the specific job, you could benefit from a resume objective.</p>
          <p class="font-14">A resume objective can explain why you are qualified for the job, even if you do not have a lot of related experience.</p>
        </div>

        <div class="mb-3">
          <h6 class="font-weight-bold">How to Write a Strong Resume Objective?</h6>
          <p class="font-14">If you include an objective in your resume, it's important to customize the resume objective to match the position you are applying for. The more specific you are, the better chance you have of being considered for the job you are interested in. It is a good idea to write a new resume objective for each job you apply for.</p>
          <p class="font-14">When you’re crafting your resume objective, you should focus on particular skills and experiences that are directly related to the job. Another effective strategy is to include keywords from the job listing in your resume objective. Not only can this increase the chances of your resume getting picked up by a company’s applicant tracking system; it can also emphasize how your qualifications align with the job listing.</p>
          <p class="font-14">You should also only state career goals that are feasible within the company. For example, if you ultimately want to become a managing editor at a magazine, but you are applying for a job at a newspaper, do not state this. Focus on how you want to grow within the company.</p>
          <p class="font-14">One of the dangers of a resume objective is that you can focus too much on what you want in your career, and not enough on how you will add value to the company. Therefore, while your resume objective should include information on the career that you want, you also want to explain why you are an ideal candidate for the job. Briefly include any information that highlights your experience, including your years in the industry, your particular skill set, and any other qualifications. Include examples of ways you could add value or even improve the company.</p>
        </div>

        <div class="mb-3">
          <h6 class="font-weight-bold">Sample Resume Objective Statements</h6>
          <ul class="font-14">
            <li>Seeking a position at XYZ Company where I can maximize my 10+ years of management, quality assurance, program development, and training experience.</li>
            <li>Seeking a position as a clinical practice assistant for a health maintenance organization, utilizing my award-winning writing, research, and leadership skills.</li>
            <li>Elementary education teacher looking for a position at a small independent school, where I can apply my five years of teaching experience and my curriculum development skills.</li>
            <li>Customer service manager seeking an opportunity to use my customer service and management skills to improve customer satisfaction.</li>
            <li>Looking for a position where I can integrate strategies to develop and expand existing customer sales, brand and product evolution, and media endorsement.</li>
            <li>Search engine optimization position where I can use my SEO skills and experience to increase site traffic and search engine placement, and apply my 15 years of IT experience.</li>
            <li>To obtain a position that will enable me to use my strong organizational skills, award-winning educational background, and ability to work well with people.</li>
          </ul>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/resumes/_hobby_fields.html.erb
<div class="nested-fields">  
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, id: :resume_name, class: "form-control", rows: "4" %>
  </div>
   <div class="form-group row">
    <div class="col-md-6">
       <%= link_to_remove_association "Remove hobbies", f, class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/resumes/_project_fields.html.erb
<div class="nested-fields">  
  <div class="form-group row">
    <div class="col-md-12">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-md-6">
      <%= f.label :role %>
      <%= f.text_field :role,  class: "form-control" %>
    </div>
    <div class="col-md-6">
      <%= f.label :duration %>
      <%= f.text_field :duration,  class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-12">
      <%= f.label :description %>
      <%= f.text_area :description,  class: "form-control", rows: "3" %>
    </div>
    <div class="col-md-12">
      <%= f.label :project_url %>
      <%= f.text_field :web_url,  class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-md-6">
      <%= link_to_remove_association "Remove Project", f, class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/resumes/_skill_fields.html.erb
<div class="nested-fields">  
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, id: :resume_name, class: "form-control", rows: "4" %>
  </div>
   <div class="form-group row">
    <div class="col-md-6">
      <%= link_to_remove_association "Remove skills", f, class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/resumes/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-md-auto">
      <h1>Editing Resume</h1>
      <%= render 'form', resume: @resume %>
    </div>
  </div>
</div>

app/views/resumes/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-12">
      <% unless @resumes.empty? %>
        <h1>Resumes</h1>

        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Name</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @resumes.each do |resume| %>
              <tr>
                <td><%= resume.name %></td>
                <td><%= link_to 'Show', resume %></td>
                <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
                <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <br>

        <%= link_to 'New Resume', new_resume_path, class: "btn btn-dark" %>
      <% else %>
        <div class="card rounded-0">
          <div class="card-body text-center">
            <p class="lead">Hey! <span class="text-primary"><%= current_user.email %></span> you have not created any resume yet. Please click onto button below to create your first resume. </p>
            <%= link_to 'New Resume', new_resume_path, class: "btn btn-dark" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/resumes/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-md-auto">
      <%= render 'form', resume: @resume %>
    </div>
  </div>
</div>

app/views/resumes/show.html.erb
<div class="container">
  <div class="row mt-5 mb-5">
    <div class="col-md-12">
      <div class="card rounded-0">
        <div class="card-body">
          <div class="row">
            <div class="col-md-9">
              <p class="mb-0"><strong><%= @resume.name %></strong></p>
              <p class="mb-0 text-underline text-primary"><span><%= @resume.email %></span></p>
              <p class="mb-0"><span>+91 <%= @resume.contact %></span></p>
              <p class="mb-0"><small><%= @resume.address %></small></p>
              <p class="mb-0"><small><%= "#{@resume.city}, #{@resume.state}, #{@resume.country}, #{@resume.zipcode}" %></small></p>
            </div>
            <div class="col-md-3">
              <%= image_tag @resume.image_url, class: "img-fluid resume-user-img" %>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-12">
              <div class="section-content pl-3 pt-1 pb-1">
                <h4 class="font-weight-bold mt-1">Objective</h4>
              </div>
              <p class="font-14 mt-2"><%= @resume.objective %></p>
            </div>
            <% if @resume.academic_credentials.present? %>
              <div class="col-12">
                <div class="section-content pl-3 pt-1 pb-1">
                  <h4 class="font-weight-bold mt-1">Educational Details</h4>
                </div>
                <table class="table table-bordered mt-2">
                  <thead>
                    <tr>
                      <th>No.</th>
                      <th>Course</th>
                      <th>Year</th>
                      <th>Percentage</th>
                      <th>Grade</th>
                      <th>Board/University</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @resume.academic_credentials.each_with_index do |value, index| %>
                      <tr>
                        <td><%= index+1 %></td>
                        <td><%= value.course %></td>
                        <td><%= value.year %></td>
                        <td><%= value.percentage %></td>
                        <td><%= value.grade %></td>
                        <td><%= value.board_or_univercity %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            <% end %>

            <% if @resume.skills.present? %>
              <div class="col-12 mb-4 mt-2">
                <div class="section-content pl-3 pt-1 pb-1">
                  <h4 class="font-weight-bold mt-1">My Skills</h4>
                </div>
                <p class="mt-3 font-14"><%= @resume.skills.pluck(:name).join(', ') %></p>
              </div>
            <% end %>

            <% if @resume.projects.present? %>
              <div class="col-12">
                <div class="section-content pl-3 pt-1 pb-1">
                  <h4 class="font-weight-bold mt-1">Projects Details</h4>
                </div>
                <% @resume.projects.each_with_index do |project, index| %>
                  <div class="card rounded-0 mt-3">
                    <div class="card-header bg-cust-header rounded-0">
                      <h6 class="card-title font-weight-bold mb-0"><%= index+1 %>. <%= project.title %></h6>
                    </div>
                    <div class="card-body">
                      <h6 class="mt-2 font-14"><span class="font-weight-bold">Role:</span> <%= project.role %></h6>
                      <h6 class="mt-2 font-14"><span class="font-weight-bold">Duration:</span> <%= project.duration %></h6>
                      <h6 class="mt-2 font-14"><span class="font-weight-bold">Url:</span> <span class="text-underline text-primary"><%= project.web_url %></span></h6>
                      <h6 class="mt-2 font-14"><span class="font-weight-bold">Description:</span> <%= project.description %></h6>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>

            <% if @resume.achievements.present? %>
              <div class="col-12 mb-4 mt-4">
                <div class="section-content pl-3 pt-1 pb-1 mb-3">
                  <h4 class="font-weight-bold mt-1">My Achievements</h4>
                </div>
                <% @resume.achievements.each_with_index do |achievement, index| %>
                  <p class="mb-0 font-14"><%= index+1 %>. <%= achievement.title %> </p>
                <% end %>
              </div>
            <% end %>

            <% if @resume.hobbies.present? %>
              <div class="col-12 mb-4 mt-2">
                <div class="section-content pl-3 pt-1 pb-1">
                  <h4 class="font-weight-bold mt-1">My Hobbies</h4>
                </div>
                <p class="mt-3 font-14"><%= @resume.hobbies.pluck(:name).join(', ') %></p>
              </div>
            <% end %>

            <div class="col-12">
              <div class="card rounded-0 mt-2">
                <div class="card-header bg-cust-header rounded-0">
                  <h4 class="card-title font-weight-bold mb-0">Personal Details</h4>
                </div>
                <div class="card-body">
                  <div class="row">
                    <div class="col-md-3">
                      <h6 class="font-weight-bold font-14 float-right">Mother :</h6>
                    </div>
                    <div class="col-md-9">
                      <h6 class="font-14 float-left"><%= @resume.mother_name %></h6>
                    </div>
                    <div class="col-md-3">
                      <h6 class="font-weight-bold font-14 float-right">Father :</h6>
                    </div>
                    <div class="col-md-9">
                      <h6 class="font-14 float-left"><%= @resume.father_name %></h6>
                    </div>
                    <div class="col-md-3">
                      <h6 class="font-weight-bold font-14 float-right">Cast :</h6>
                    </div>
                    <div class="col-md-9">
                      <h6 class="font-14 float-left"><%= @resume.cast %></h6>
                    </div>
                    <div class="col-md-3">
                      <h6 class="font-weight-bold font-14 float-right">Relegion :</h6>
                    </div>
                    <div class="col-md-9">
                      <h6 class="font-14 float-left"><%= @resume.relegion %></h6>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-12">
              <p class="font-14 font-weight-bold mt-4 mb-2">* I hereby declared that all the information provided above are correct.</p>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
  <button id="print-btn" class="btn btn-success mb-2">Print or Download</button>
</div>

<script>
  $("#print-btn").on('click', function(){
    window.print();
  });
</script>

<style type="text/css">
  @media print {
    #print-btn {
      display: none;
    }
  }
</style>